version: '3.8'

services:
  ai-artistic-style-service:
    image: urmsandeep/ai-artistic-style-service:latest
    container_name: ai-artistic-style
    ports:
      - "5001:5001"
    restart: always

